version: '2'

services:

  taiga-client:
    build:
      context: .
      dockerfile: ./.docker/development.dockerfile
    command: npm start
    container_name: taiga-client-start
    image: taiga-client
    networks:
      - dev-network
    ports:
      - '4200:4200'
    volumes:
      - .:/home/app/taiga-client

networks:
  dev-network:
    driver: bridge